<?php
/**
* @file
* Generates a Twitter Bootstrap Carousel with images carousel.
*
*/

/**
 * Implements hook_theme().
 */
function blueimp_theme($existing, $type, $theme, $path) {
  return array(
    'block_gallery' => array(
      'variables' => array('data' => NULL),
    ),
  );
}

function blueimp_check_path($visibility, $pages) {
  $pages = \Drupal\Component\Utility\Unicode::strtolower($pages);
  $current_path = \Drupal::service('path.current')->getPath();

  //$path_alias = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  //refs: https://www.drupal.org/node/1853148

  // Convert the Drupal path to lowercase
  $path = \Drupal\Component\Utility\Unicode::strtolower($current_path);
  // Compare the lowercase internal and lowercase path alias (if any).
  $page_match = \Drupal::service('path.matcher')->matchPath($path, $pages);
  if ($path != $_GET['q']) {
    $page_match = $page_match || \Drupal::service('path.matcher')->matchPath($current_path, $pages);
  }
  // When $block->visibility has a value of 0 (BLOCK_VISIBILITY_NOTLISTED),
  // the block is displayed on all pages except those listed in $block->pages.
  // When set to 1 (BLOCK_VISIBILITY_LISTED), it is displayed only on those
  // pages listed in $block->pages.
  $page_match = !($visibility xor $page_match);
  return $page_match;
}

/**
 * Check if the Blueimp library is installed.
 *
 * @return
 *   A boolean indicating the installed status.
 */
function blueimp_installed() {
  if (($library = libraries_detect('blueimp')) && !empty($library['installed'])) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Check if the Blueimp library has been loaded.
 *
 * @return
 *   A boolean indicating the loaded status.
 */
function blueimp_library_loaded() {
  if (($library = libraries_load('blueimp')) && !empty($library['loaded'])) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

function _blueimp_render($module, $block_id) {
  $block = block_load($module, $block_id);
  $block_content = _block_render_blocks(array($block));
  $build = _block_get_renderable_array($block_content);
  $block_rendered = \Drupal::service("renderer")->render($build);
  return $block_rendered;
}
